keys:
  - &host age145uvzwjzua4kl0c89dmat00pgz3srfmf4wfzzalnszk5ae6t043ss8x4jj
  - &redis age1mafl38hjx62tk6s7r4kqujras23rlnxzeqv53pcuaff7u03d4eus9n5nzu
  - &vault age1n95yuqarzpvja5w28mqdj2vfg0629ytlp68zfdvhexn9n3xj6vmqvzn8hw
  - &keycloak age1m4yddkn9zwkrk2c457l9kgwxwy35l3256r2hcd6h29fljjxvgd3sher6wq
  - &docker age1cnhzp45jmyqfwgxnuyj84lz2uf0jcf20xk4u5n47fs24fdvr6szshg9jzw
creation_rules:
  - path_regex: secrets/redis.*\.ya?ml$
    key_groups:
      - age:
          - *host
          - *redis
  - path_regex: secrets/vault.*\.ya?ml$
    key_groups:
      - age:
          - *host
          - *vault
  - path_regex: secrets/keycloak.*\.ya?ml$
    key_groups:
      - age:
          - *host
          - *keycloak
  - path_regex: secrets/docker.*\.ya?ml$
    key_groups:
      - age:
          - *host
          - *docker